language: node_js
node_js:
  - "10"
after_success:
  - yarn build
before_deploy:
  - cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: MaIDgtCGAXo8kbHTlQ6m0husGnLcq2MDi19kl7kLZwB5J3hV0Nsq1Yna7ox6Sob33rFdeRpcvD6b+V8qsztIRRdD32roo+ApOGlsTTTzZe1ZUtuthfTfDqCE62pMTlfr6OmRGNQDLxR5rAEj90g2V7g1KvDHpuPc7I5sThUSd7LRh0nZe/T3JkRZcbvLazfK7H36lN3BNk8MjuQsSBUhYwvdtE2h2i3nksC8ja7EVE7dd3btFmdmidcMZF9YaW0b6RwLvzMH8F5AEuBCR11pd7cChv3jpSdoQ1iUhNZii1ODcJ4XbftI9lr8jsxT8Mp8P6lAElm+cy6nLRHBYCrS94dDt/pNv1hjKPP5cXLLOsPMkbl5hYZpaSnYbBcHh+4VgAECB7FTMFwvD8QJzw/srbDVOtr1q6jHpmiUKaWV1Qst/Mdluwi0yzDaN0HbEAr5Ouvls3K6J0MCvJfLOpPyKGrcPXcNtJewfDQkjIvA+PhUKrxIhaGHWNxvZRIOfQ58lmxiRi+lYkHgCkLPYYpyjjzriSsskKI9I07pbNE2R9LHO3fspCHdnNsTZyVCKcWlp2/1Kn9vZNqVD59LzaNoOJzRf6Z6i6o3CiZLnxL89XgsmXEkVzlkZcEXf1PO6GYRbT4pldOk94qDD6jr/gbNYXgRY0ezlmlf0pZsIumodM4=
  app: botblist
  skip_cleanup: true
  on:
    repo: jgretz/botb-list
