language: node_js
node_js:
- '10'
after_success:
- yarn build
before_deploy:
- cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: U8xhX7uydxHcn6wC9s8V4dqogjyOZzvkW1PVruouVJxCNeWGlyQi1jihJcS/XS0Y7glKnwrZ/Ms8FLpOmSvhbHiC9+T+Rn8Ap5NdudKBbgatRhY66hLilYSU0ShZ0YxbNTOVYWG8ECbDyrfqDqNtT3O+euo8YJIH3vm4fmJfh1nbdaSz16Ok4iXbXK6zBflAL9ap6t2p/6IgC9PCiQw4bArbl4KqLhG8REMpuLxDlo4JTnuyedSqqDgfvJLOKn9nuNajugJNwymev5Frinu6vtaETtUUjMmHIVosSxKXcmW7iav2NMmGm4HdcrqHDnHCCmnxToXYiikMJgNkGmDXk4gwuq8ewHu4S3MnXKEyiGfXiyk8HIzTkfLdBxQXClS3V5dPfeCXW1at16UWWzMQkAkXH/AejisvPWh7jUbu+cE1a8DQu+Z670fs9v2KmTPeqwg0Gq2rN7vDALZXSgHLN8f8T/oiUOrFHPc00RE30VgNeJnQMF8c0kxY+Bpa9XLemnKvXzDYmr5j+j37+TItk7PeawBaTbR/VNSBpE/x1KeXSNsiool4wIOAtEfZk6Ixw9DLbgFUiGlkGiPSv6mLplihorKpvJscm5xh6iMfQKTXpFpD+ajleecsDi8oXo2vHMVYvFNXmask5hHQKUiY6f4SebTjNDr/p1QO8LooW5c=
  app: botblist
  skip_cleanup: true
  on:
    repo: jgretz/botb-list
