language: node_js
node_js:
- '10'
after_success:
- yarn build
before_deploy:
- cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: NNzAvrv/XmYUSpI2atyoRm4VWSsRrFHKpKQTo99DHWm33IM4TjahiiTKDKNcREmuqCOpb3dGsQeFRu2Qx5kqC+1ufgCKbivUWHRZasKepQZw+wrbrBVaok9RrRCyi4yqoNbhKgu4CVpEUR7Hd6/FkJLJBSqORdIPh/lOQ4Z6qYQDOsXtnxuvcVJQd4qgkk2UQvi9CWq6zNBn2C19EFpA05nHELdUGR2uwxNqnSdhR240/EGFxOMgzlv3IQIc/mOeChtREv5Ui2k+dGUFE4gXir4WFBvuem7XlAfRx2suo3KPK7vSzypRCOblzOd1Y1RBumrX1UT8RqmfDYMMpKmAvEalUfWqaoEEE3dHGIdYGAdbdsjBRRyiWlBqKyOaf7Je3oOYW6odxJFxKD48aDqtjaSaWW7UdgMscCCI38w05exyw2/eZk2nSabR7EodguXGevnTmMYsz6dLmkaMxprMYRbqVurEFoU08+a7HPtlu4JMOeiS9GNWSyJQzx8ljDR/Kkk2wEXwIwuHGAIYx+XQ5fD4Dg2tvOm0sFh02WJhkrhHJalCRKmP/9yy3fmfRZm+FsIfovK2NmkKogMbAGFYmj7EgXMvisjegQXjbz4fcLk+JUu1Vb/93LCUx3XPQEI7qNqLIPBjS2i9R00ErTHl3QFBSYfGt9PsEQnjJIatmh0=
  app: botblist
  on:
    repo: jgretz/botb-list
