language: node_js
node_js:
- '10'
after_success:
- yarn build
before_deploy:
- cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: gTKsc6DxspF935TwBZQxMbCKkx+fcnBRv+QC0iKM4T9WcM8hIde0SWzA8HYP2BYuMbgrZcC4Y86fkGNuffPC/caBk/a5VmTUmFkDLFzlVpvGSkti2hWc9ZymuHx0o8l0Co6FfRMGIk0PanFPnl50aDLFespCpKems4HVx/NC4HCVroC6idKvA3CAupy1MHXq0qy1TSOJe+PDXPjLVaZi4V3f9IpvYCv1W9KBfrvUtgQF4XY72APfCVoFIN8I9THeEhRt+FmdAk/FOt8XGKz4CeG1c1FUktJ1jdaEfAxuojeEbL34d2166GbFCJ6q7EOxyJxl2zGfuqxMKSkXHIqxXVbhFYVwWcwzLORonX/sDzOE4ye7/mibJV/faQRe/ZsCXPdOlPQtjby503rkhHdjUNrDDKwVAfD73QO2bEQ8vid+2Ei2xc8qDp78gz8ldNdUCe1+7LJvSmtOwCa472hDh+az0iGgVHrUuMEaUCc+wCO4hz9r8quRPhM45JsrXJosrusgfPtRkApOg+3ObnyuJcua489h5ctevAMLnEsHypqS+oHFtniF5NkxuvLU4SC/5UG5ANTONsBnMQ2RmtRrmgNlaM77WMAvJE0DhMhtFB+4mkhkUnzbNlrhp7xT3+HweJyapwAyhuRyuCIqloIYBGq3D2fI3ODc1wWV93jRyyE=
  app: botblist
  on:
    repo: jgretz/botb-list
