language: node_js
node_js:
- '10'
after_success:
- yarn build
before_deploy:
- cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: konV04g1q0ILjS4SNjZ+3BbW7MjV7Pwz8e7p4W2i0Ea89GtZIokfbIE5qsz/CB0AVaG13GpzTdQujUn29l6R5YqCYQc6Qn4NYuYN+VqKtvPOhwaR/5SHQGI8Ft+YVcw5EI+u9qE6VdFbL98Gr2xM5+PgF5LG9kuyg3Z+QkvvTI7p8lxuxomNcYH21XVvA711B/t/xU4Rd4Lhv3fPTtdSWnnUOM2Ym1fEjWOhxlhEz2pYFPrIPgiB2YBMMsk/RFNzYqtzSFrA0pTGtMxe5yDPgyqItkUQcGRqJSF7Ewc9PG++lCMqi0trPRvNyQYGUsLILCymtSL8+Up19y3SjDRrUHdVYPqSjJIFCSfgLEHRPG6K9G86yb3CfKwAaGJFZTKFklxmUWzkCyuj6AxpFYwbEjRtQWwyvZn9IpwNiuUB1NqCmkyxJy3p7htkG3KJgRly4z1XwnSZLEBz90yOS7yH9ajK6SVHtNvlwBoNTNKPLBfadVt8qsMD6WqGR/HeHfcb1saWm7J7WQkV7jGIaG157pIR30o3239CKh11prBdjyNNPqIfqzGuMrsDqiECvfTat1PTnPA34xLustsXyh0kcjRWZJpGFjSJQK6+6FmihBzqya35iuiVztA3iQwy76P8pk4le+3lraJ5SON+8Hh25CMo/bmjBvY43dkPuA4dspg=
  app: botblist
  skip_cleanup: true
  on:
    repo: jgretz/botb-list
