language: node_js
node_js:
  - "10"
after_success:
  - yarn build
before_deploy:
  - cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: IrG7CQnbhJnve3rVE/H3YwUkCHryCbOn8xmcIr/XQsOXRnQDOF+Dp8bZtNjoRSAqXAqNbVUCEbsBmF1i0RnzQCxvmJooBzjFPNDNq8JSgnl6uZYBMeYtGjrt3TZ2fTEYEngb9jynejGHWt4uEZQJNmIo243xlf9dqgOUrkd+free79bjC9vb7sdeg8ug9nPvudCs+K2yCFO64dku6339mHT53wud5ve0Xs97VJ2/EWdzFH2CCZ2ltKfElcsKBtLP+X30DLerFdNoVvY0gfRvfmaVpla15e76CzDtuvzkGCsbDok5en8HP2pYGE5QTamTmpssihXdt5OumwWPrITTiVP53fNHwTzMoh2dtiI0mZrPzUJqhp8XkadopDnKlZ3jJVxXRQQRKdsI6ZEZ5eGDe+LFqO8Iz9IRuSPEjIFIXLSONi8Cs5Fb/zHwtEbESHiI/2jR9U4O/uNpoABF/ch+oyCi/E+N8831PMKe6wdv71cnC+cIJk278R5UG+WnxG69QDHUKZIESjAtNZHhXgkIHEyBqW3kHHfGWOxz9jcZoeZzhU11q2PcNunyiw2jKNh1X1IuUwTyx27XJonPmMSPrjkwQD5cVbX20XpZR+6c1dLomn5P9SmdJaInIY6v18oCPUa8I3EHrx91QizMCQoUDrH2j+dmYRimFuoYAZcwXRs=
  app: botblist
  skip_cleanup: true
  on:
    repo: jgretz/botb-list
