language: node_js
node_js:
  - "10"
after_success:
  - yarn build
before_deploy:
  - cd ./lib
deploy:
  provider: heroku
  api_key:
    secure: PT/ifcu79SvFcUQ2kbr0Z9qJWGNMtXONAmBlcRs2N/MTDeLsDlVV5IEGfvra4cLRKpKRejxTIZxLEp392EJV1PpDd7oB7DhfHComiMa4MdOZpPGWxkBJJCpVjauibZAez/I823Ey7rpDU5+23UuEf1YG5Kud1zvQ7vH7SeUK9eNKyysFl0/CN3WnCefJqjgCujo6ABSMEu3bQGohviIf2mG22OXR4bqUDHphfOKQziW1fUIk+OJrfJZ8hsMAN64QTozAfYzTu7LIfmWWYzeIgSi/4oj7AZ1x2TW80dNUuepR/YI/NxZ+O/+AKlHXP78ZNKw8wQNeZeEkl3lnY3/tmW8dj6Imd9//AdCLJY8jdGaW40opdA/P5LRMwKzQ7FNIis612HEUxV0z7oqxQhSbOnKCpnzxfArwm15UbcSmffuZTyLh12ztt7TbhFpGFuztxoOF8jsUQ3MkLkYQAtZhYWKBkhT+YN4ZT+84wmhZZv72qU+VsAX5Gt+QcvMhCzlEL/gzJTH7iq1RGK6xu2PR8Ti1jVt2GyeOVB3zVnP0musBiUj0f7GuWZWcA5eXmrhLo9UmqraGvryP7OhbUwVTni5TNaFzk0DcMZeYKAOLGuOqZTswcTcNTfGiVbbl/gyWQBbckyHhpERoVInAulzdHR37lNshQS9Wzmk+kZSiYUY=
  app: botblist
  skip_cleanup: true
  on:
    repo: jgretz/botb-list
